src/Entity/Customers.php
<?php

namespace App\Entity;

use App\Repository\CustomersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CustomersRepository::class)
 */
class Customers
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Customer_name;

    /**
     * @ORM\Column(type="date")
     */
    private $Birth_day;

    /**
     * @ORM\OneToMany(targetEntity=Orders::class, mappedBy="customers", cascade={"persist"})
     */
    private $order;

        public function __construct()
    {
        $this->order = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCustomername(): ?string
    {
        return $this->Customer_name;
    }

    public function setCustomername(string $Customer_name): self
    {
        $this->Customer_name = $Customer_name;

        return $this;
    }

    public function getBirthDay(): ?\DateTimeInterface
    {
        return $this->Birth_day;
    }

    public function setBirthDay(\DateTimeInterface $Birth_day): self
    {
        $this->Birth_day = $Birth_day;

        return $this;
    }

            /**
     * @return Collection|Orders[]
     */
    public function getOrders(): Collection
    {
        return $this->order;
    }

    public function addOrders(Orders $order): self
    {
        if (!$this->order->contains($order)) {
            $this->order[] = $order;
            $order->setCustomers($this);
        }

        return $this;
    }

    public function removeProduct(Orders $orders): self
    {
        if ($this->order->removeElement($orders)) {
            // set the owning side to null (unless already changed)
            if ($orders->getCustomers() === $this) {
                $orders->setCustomers(null);
            }
        }

        return $this;
    }
}

src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrdersRepository::class)
 */
class Orders
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\ManyToOne(targetEntity=Products::class, inversedBy="orders", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\ManyToOne(targetEntity=Customers::class, inversedBy="orders", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $customer;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }
    
    public function getProducts(): ?Products
    {
        return $this->product;
    }

    public function setProducts(?Products $products): self
    {
        $this->product = $products;

        return $this;
    }

    public function getCustomers(): ?Customers
    {
        return $this->customer;
    }

    public function setCustomers(?Customers $customers): self
    {
        $this->customer = $customers;

        return $this;
    }
}

src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductsRepository::class)
 */
class Products
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

        /**
     * @ORM\Column(type="string", length=255)
     */
    private $productName;

    /**
     * @ORM\ManyToOne(targetEntity=Suppliers::class, inversedBy="products")
     */
    private $supplier;

    /**
     * @ORM\Column(type="integer")
     */
    private $Price;

    /**
     * @ORM\OneToMany(targetEntity=Orders::class, mappedBy="product", cascade={"persist"})
     */
    private $order;

    public function __construct()
    {
        $this->order = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setID(int $id): self
    {
        $this->id = $id;

        return $this;
    }

        public function getProductName(): ?string
    {
        return $this->productName;
    }

    public function setProductName(string $productName): self
    {
        $this->productName = $productName;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getSuppliers(): ?Suppliers
    {
        return $this->supplier;
    }

    public function setSuppliers(?Suppliers $suppliers): self
    {
        $this->supplier = $suppliers;

        return $this;
    }

        /**
     * @return Collection|Orders[]
     */
    public function getOrders(): Collection
    {
        return $this->order;
    }

    public function addOrders(Orders $order): self
    {
        if (!$this->order->contains($order)) {
            $this->order[] = $order;
            $order->setProducts($this);
        }

        return $this;
    }

    public function removeOrders(Orders $orders): self
    {
        if ($this->order->removeElement($orders)) {
            // set the owning side to null (unless already changed)
            if ($orders->getProducts() === $this) {
                $orders->setProducts(null);
            }
        }

        return $this;
    }
}

src/Form/OrdersType.php
<?php

namespace App\Form;

use App\Entity\Orders;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class OrdersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            
            ->add('Products', ProductsType::class)
            ->add('Date', DateType::class, [
                'years' => range(2023, 1990)
            ])
            ->add('Customers', CustomersType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Orders::class,
        ]);
    }
}

src/Controller/OrdersController.php
<?php

namespace App\Controller;

use App\Entity\Orders;
use App\Form\OrdersType;
use App\Repository\OrdersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\AbstractType;
/**
 * @Route("/orders")
 */
class OrdersController extends AbstractController
{
    /**
     * @Route("/", name="app_orders_index", methods={"GET", "POST"})
     */
    public function index(OrdersRepository $ordersRepository): Response
    {
        return $this->render('orders/index.html.twig', [
            'orders' => $ordersRepository->findAll(),
        ]);
    }
    /**
     * Create a new order.
     * 
     * @Route("/new", name="app_orders_new", methods={"GET", "POST"})
     */
    public function new(Request $request, OrdersRepository $ordersRepository): Response
    {
        $order = new Orders();
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ordersRepository->add($order);
            $ordersRepository = $this->getDoctrine()->getManager();
            $ordersRepository->persist($order);
            $ordersRepository->flush();
            
            return $this->redirectToRoute('app_orders_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('orders/new.html.twig', [
            'order' => $order,
            'form' => $form,
        ]);
    }

    /**
   *
   * @Route("/{id}",methods={"GET"} ,name="app_orders_show")
   */
  public function showAction(Orders $orders)
  {
    $deleteForm = $this->createDeleteForm($orders);

    return $this->render('orders/show.html.twig', array(
      'orders' => $orders,
      'delete_form' => $deleteForm->createView(),
    ));
  }

  /**
     * @Route("/{id}/edit", name="app_orders_edit", methods={"GET", "POST"})
     */
  public function editAction(Request $request, Orders $orders)
  {
    $deleteForm = $this->createDeleteForm($orders);
    $editForm = $this->createForm(OrdersType::class, $orders);
    $editForm->handleRequest($request);

    if ($editForm->isSubmitted() && $editForm->isValid()) {
      $this->getDoctrine()->getManager()->flush();

      return $this->redirectToRoute('app_orders_edit', array('id' => $orders->getId()));
    }

    return $this->render('orders/edit.html.twig', array(
      'orders' => $orders,
      'edit_form' => $editForm->createView(),
      'delete_form' => $deleteForm->createView(),
    ));
  }

  /**
   *
   * @Route("/orders/{id}", name="app_orders_delete")
   */
  public function deleteAction($id)
  {
    $em = $this->getDoctrine()->getManager();
    $orders = $em->getRepository('App\Entity\Orders')->find($id);
    $em->remove($orders);
    $em->flush();
    
    $this->addFlash(
        'error',
        'Orders deleted'
    );

    return $this->redirectToRoute('app_orders_index');
  }

  /**
   *
   * @param Orders $orders The order entity
   *
   * @return Form The form
   */
  private function createDeleteForm(Orders $orders): Form
  {
    return $this->createFormBuilder()
      ->setAction($this->generateUrl('app_orders_delete', array('id' => $orders->getId())))
      ->setMethod('DELETE')
      ->getForm();
      
  }
}

templates/orders/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Orders{% endblock %}

{% block body %}
    <h1>Edit Orders</h1>
    {{ form_start(edit_form) }}
    {{ form_widget(edit_form) }}
    <input type="submit" value="Update" />
    {{ form_end(edit_form) }}

  <ul>
    <li>
      <a href="{{ path('app_orders_index') }}">Back to the list</a>
    </li>
    <li onclick = "return confirm('Are u sure u want to delete?')">
      {{ form_start(delete_form) }}
      <input type="submit" value="Delete">
      {{ form_end(delete_form) }}
    </li>
  </ul>
{% endblock %}

templates/orders/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders index{% endblock %}

{% block body %}
    <h1>Orders</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Customer</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.Date ? order.Date|date('Y-m-d') : '' }}</td>
                <td>{{ order.customers.customername }}</td>
                <td>
                    <button><a href="{{ path('app_orders_show', {'id': order.id}) }}" class="btn btn-success">show</a></button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No Records Found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/orders/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h1>Add new order</h1>

	{{ form_start(form) }}
	{{ form_widget(form) }}
	<button input type="submit" value="Create">Create</button>
	{{ form_end(form) }}

    <button><a href="{{ path('app_orders_index') }}">Back to the list</a></button>
{% endblock %}

templates/orders/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders{% endblock %}

{% block body %}
    <h1>Orders</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ orders.id }}</td>
            </tr>
            <tr>
                <th>Product</th>
                <td>{{ orders.products.productName }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ orders.Date|date('d-m-Y') }}</td>
            </tr>
            <tr>
                <th>Customer</th>
                <td>{{ orders.customers.customername }}</td>
            </tr>
            <tr>
                <th>Total</th>
                <td>{{ orders.products.price }}$</td>
            </tr>
        </tbody>
    </table>
    <ul>
        <ul>
        <button><a href="{{ path('app_orders_index') }}">back to list</a></button>
        </ul>
    </ul>
{% endblock %}